### ISSUE TITLE
Can you share weights or model?

### ISSUE THREAD

**Issue by Asteur** [robgon-art/MAGnet#1]
Hi Robert,

Thanks for sharing your work, looks cool.
Can you share weights or model?

Thanks

**Comment by Asteur** [comment]
Found, thanks

**Comment by robgon-art** [comment]
OK, in case others are looking for the weights, the trained model can be downloaded here:
  https://drive.google.com/file/d/15-bJ9QyLGJqd97pAK9_O12cEQV9591o8/view?usp=sharing
  
It can be downloaded in Python like this:
`# MAGnet_250.pt`
`!gdown --id 15-bJ9QyLGJqd97pAK9_O12cEQV9591o8`

Note that the model uses the SWAGAN architecture.

See the source code on the **Initialize the System** section in https://colab.research.google.com/github/robgon-art/MAGnet/blob/main/5_MAGnet_Generate_Modern_Paintings.ipynb for the code using the model.
